version: "3.1"
services:
  db:
    image: mysql:5.7.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pizza_delivery
    volumes:
      - ./mysql_data:/var/lib/mysql
